image: ubuntu:18.04

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - apt-get -qq update
    - apt-get -qq install software-properties-common
    
    - add-apt-repository ppa:webupd8team/java
    - apt-get -qq update
    
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections
    - apt-get -qq install oracle-java8-installer
    
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    stage: build
    script:
        - ./gradlew --build-cache assemble
#    only:
#        - master
#        - develop
#        - tags
    cache:
        key: "$CI_COMMIT_SHORT_SHA"
        policy: push
        paths:
            - build
            - .gradle

test:
    stage: test
    script:
        - ./gradlew --build-cache check
#    only:
#        - master
#        - develop
#        - tags
    cache:
        key: "$CI_COMMIT_SHORT_SHA"
        policy: pull
        paths:
            - build
            - .gradle

