image: ubuntu:18.04

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export DEBIAN_FRONTEND=noninteractive

    - apt-get -qq update
    - apt-get -qq install --no-install-recommends apt-utils > /dev/null
    - apt-get -qq install --no-install-recommends software-properties-common > /dev/null
    
    - add-apt-repository ppa:webupd8team/java > /dev/null
    - apt-get -qq update
    
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections
    - apt-get -qq install --no-install-recommends oracle-java8-installer > /dev/null
    
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    stage: build
    script:
        - ./gradlew clean assemble
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull-push
        paths:
            - build
            - .gradle

test:
    stage: test
    script:
        - ./gradlew --build-cache check
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - build
            - .gradle

