language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git libglpk-dev libglpk-java
  - echo glpkJava=$(dpkg -L libglpk-java | egrep 'libglpk_java.so$') > gradle.properties
  - echo glpk=$(dpkg -L libglpk-dev | egrep 'libglpk.so$') >> gradle.properties
